Filtering - Using Conditionals to Filter Rows and Columns

In [1]:
import pandas as pd
people={
    "First" :["Siddhant","Rupaniwta","Karan"],
    "Last" :["Roy","Sahani","Yadav"],
    "Email":["siddhantroy@gmail.com","rupaniwtasahani@gmail.com","karanyadaav@gmail.com"]
}
df=pd.DataFrame(people)
df

       First    Last                      Email
0   Siddhant     Roy      siddhantroy@gmail.com
1  Rupaniwta  Sahani  rupaniwtasahani@gmail.com
2      Karan   Yadav      karanyadaav@gmail.com

Making a filter and then searching for that filter in that dataframe:

In [12]:
filt=(df["Last"]=="Roy")
filt                #filt is a series of bool expressions with True and False if the condition matches it shows True otherwise False 

#Now we will search for that filter in the dataframe:
df[filt]

<class 'pandas.core.series.Series'>

      First Last                  Email
0  Siddhant  Roy  siddhantroy@gmail.com

Another Way to filter data : Using loc() function , because you can also filter a specific column with that filter together :

In [3]:
filt=(df["Last"]=="Roy")
df.loc[filt,"Email"]   #you can see that we used the filter to search for the row which have Roy as last name and then further we accessed the Email with it

0    siddhantroy@gmail.com
Name: Email, dtype: object

Filtering data using conditions (& and |)

In [17]:
df_2=pd.read_csv("Pokemon.csv")
df_2

#Show the records where Attack is greater than 70 and Type 1 is Grass:

df_2.loc[(df_2["Attack"]>=70) & (df_2["Type 1"]=="Grass")]

#U can directly put the conditions inside the loc or use a variable to store the filter and then pass it inside the loc().

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
62,57,Primeape,Fighting,NaN,455,65,105,60,60,70,95,1,False
82,76,Golem,Rock,Ground,495,80,120,130,55,65,45,1,False
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
52,47,Parasect,Bug,Grass,405,60,95,80,60,80,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
160,148,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False
110,102,Exeggcute,Grass,Psychic,325,60,40,80,60,45,40,1,False
160,148,Dragonair,Dragon,NaN,420,61,84,65,70,70,70,1,False
110,102,Exeggcute,Grass,Psychic,325,60,40,80,60,45,40,1,False

In [5]:
#Using a variable to store the filter :
filt2= (df_2["Attack"]>=70) & (df_2["Type 1"]=="Grass")
df_2.loc[filt2]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
111,103,Exeggutor,Grass,Psychic,520,95,95,85,125,65,55,1,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
207,192,Sunflora,Grass,NaN,425,75,75,55,105,85,30,2,False
274,254,Sceptile,Grass,NaN,530,70,85,65,105,85,120,3,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
297,274,Nuzleaf,Grass,Dark,340,70,70,40,60,40,60,3,False
298,275,Shiftry,Grass,Dark,480,90,100,60,90,60,80,3,False
310,286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False
362,331,Cacnea,Grass,NaN,335,50,85,40,85,40,35,3,False
363,332,Cacturne,Grass,Dark,475,70,115,60,115,60,55,3,False
433,388,Grotle,Grass,NaN,405,75,89,85,55,65,36,4,False
434,389,Torterra,Grass,Ground,525,95,109,105,75,85,56,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
505,455,Carnivine,Grass,NaN,454,74,100,72,90,72,46,4,False
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
516,465,Tangrowth,Grass,NaN,535,100,100,125,110,50,50,4,False
521,470,Leafeon,Grass,NaN,525,65,110,130,60,65,95,4,False
550,492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
551,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
556,497,Serperior,Grass,NaN,528,75,75,95,75,95,113,5,False
571,512,Simisage,Grass,NaN,498,75,98,63,98,63,101,5,False
617,556,Maractus,Grass,NaN,461,75,86,67,106,67,60,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
659,598,Ferrothorn,Grass,Steel,489,74,94,131,54,116,20,5,False
701,640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [6]:
#If you have a filter but you want the results opposite to that filter,like above the conditions are Attack should be more than 70 and Type 1 should be Grass , if we use "~" symbol before the filter we will get the data opposite of the filter.
 
df_2.loc[~filt2]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [7]:
#Show the Type 1 and Type 2 of the pokemons which have Attack of more 70 and defence less than 50:
filt3=(df_2["Attack"]>=70) & (df_2["Defense"]<=50)
df_2.loc[filt3,"Type 1":"Type 2"]

       Type 1  Type 2
18        Bug  Poison
19        Bug  Poison
45     Normal   Fairy
56     Ground     NaN
61   Fighting     NaN
63       Fire     NaN
72   Fighting     NaN
75      Grass  Poison
76      Grass  Poison
91     Normal  Flying
95     Poison     NaN
213      Dark  Flying
216   Psychic     NaN
225     Fairy     NaN
234    Normal     NaN
247      Dark    Fire
259      Fire     NaN
280     Water     NaN
290       Bug  Flying
297     Grass    Dark
315       Bug  Flying
316       Bug   Ghost
318    Normal     NaN
347     Water    Dark
348     Water    Dark
350     Water     NaN
351     Water     NaN
359    Ground     NaN
360    Ground  Dragon
362     Grass     NaN
379      Rock     Bug
385     Ghost     NaN
428   Psychic     NaN
429   Psychic     NaN
442    Normal  Flying
449  Electric     NaN
453      Rock     NaN
461       Bug  Flying
473     Ghost  Flying
491    Dragon  Ground
495    Normal     NaN
496  Fighting     NaN
569      Dark     NaN
588    Ground     NaN
611    Ground    Dark
612    Ground    Dark
614      Fire     NaN
627      Rock  Flying
649       Bug     NaN
674       Ice     NaN
678       Bug     NaN
680  Fighting     NaN
683    Ground   Ghost
688    Normal  Flying
750     Steel   Ghost
778     Ghost   Grass

In [8]:
#Q.How many Pokémon are there from each generation?
generation_count= df_2["Generation"].value_counts().sort_index()
for gen,count in generation_count.items():
    print(f"Generation {gen} has {count} Pokémon.")
print("\n")
print(generation_count)   # it returns a series 
print(generation_count.items())      #it is an iterable object which we can access using two variables since it has a pair of values together 


#NOTE: value_counts returns a series and .items() makes the series into a iterable object of index value pair

Generation 1 has 166 Pokémon.
Generation 2 has 106 Pokémon.
Generation 3 has 160 Pokémon.
Generation 4 has 121 Pokémon.
Generation 5 has 165 Pokémon.
Generation 6 has 82 Pokémon.


Generation
1    166
2    106
3    160
4    121
5    165
6     82
Name: count, dtype: int64
<zip object at 0x000002093DFE7A80>

In [9]:
#Q.What are the most common primary and secondary types of Pokémon?

# Count the occurrences of each primary and secondary type
primary_type_counts = df_2['Type 1'].value_counts()
secondary_type_counts = df_2['Type 2'].value_counts()

common_type1=primary_type_counts.idxmax()
print(common_type1)
common_type2=secondary_type_counts.idxmax()
print(common_type2)



#NOTE: idmax() gives you the label of the value that have most occurences:
# suppose this is a series:Fire  50 , Water  80 , Normal  70
#so it will print water becoz it has the highest count

Water
Flying

In [10]:
#q.Which Pokémon have the highest total stats, and how do their individual stats (Attack, Defense, etc.) compare?

highest_total=df_2["Total"].idxmax()
df_2.loc[highest_total]

#                             150
Name          MewtwoMega Mewtwo X
Type 1                    Psychic
Type 2                   Fighting
Total                         780
HP                            106
Attack                        190
Defense                       100
Sp. Atk                       154
Sp. Def                       100
Speed                         130
Generation                      1
Legendary                    True
Name: 163, dtype: object

In [11]:
legendary=df_2["Legendary"]==True
non_legendary=df_2["Legendary"]==False
legendary_filter=df_2.loc[legendary,"Total"].items()
non_legendary_filter=df_2.loc[non_legendary,"Total"].items()
for (i , legendary_total),(j,non_legendary_total) in zip(legendary_filter,non_legendary_filter):
    if legendary_total<non_legendary_total:
        print(f"{df_2.loc[i,"Name"]} is a legendary pokemon that have low stats than non legendary pokemons")

Entei is a legendary pokemon that have low stats than non legendary pokemons
Suicune is a legendary pokemon that have low stats than non legendary pokemons
Regice is a legendary pokemon that have low stats than non legendary pokemons